# Name of website
title: gvSIG desktop

# Short description of your site
description: Documentación de gvSIG desktop


#theme: jekyll-theme-slate

# Exclude these files from production site
exclude:
#  - develdoc
#  - userdoc/manual_de_usuario
#  - userdoc/topologia
#  - userdoc/vcsgis/
#  - userdoc/vcsgis/copias_de_trabajo
#  - userdoc/vcsgis/empezando
#  - userdoc/vcsgis/repositorio
#  - userdoc/vcsgis/utilizacion_basica   
#  - userdoc/vcsgis/utilizacion_basica/ciclo_de_trabajo_basico
  
  

theme: jekyll-theme-midnight