# Name of website
title: gvSIG desktop

# Short description of your site
description: Documentación de usuario de gvSIG desktop


theme: jekyll-theme-modernist

# Exclude these files from production site
exclude:
  - all.md
  
